name: buffer
description: >
  Utility functions and classes to work with byte buffers and streams efficiently,
  to read and write binary data formats.
version: 1.1.1
homepage: https://github.com/isoos/buffer

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7
