name: buffer
description: >
  Utility functions and classes to work with byte buffers and streams efficiently,
  to read and write binary data formats.
version: 1.2.3
repository: https://github.com/isoos/buffer
topics:
  - bytes
  - stream
  - protocol
  - server
  - client

environment:
  sdk: ">=2.12.0 <4.0.0"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.7
